name: rd-culture
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py312h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - black==25.9.0
      - blessed==1.23.0
      - click==8.3.0
      - gpustat==1.1.1
      - iniconfig==2.3.0
      - jax==0.8.0
      - jax-cuda12-pjrt==0.8.0
      - jax-cuda12-plugin==0.8.0
      - jaxlib==0.8.0
      - ml-dtypes==0.5.3
      - mypy-extensions==1.1.0
      - numpy==2.3.4
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.15.0.57
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.28.7
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvshmem-cu12==3.4.5
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.3
      - pathspec==0.12.1
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - psutil==7.1.3
      - pygments==2.19.2
      - pyprojroot==0.3.0
      - pytest==8.4.2
      - python-box==7.3.2
      - python-dateutil==2.9.0.post0
      - pytokens==0.2.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - scipy==1.16.3
      - six==1.17.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - vulture==2.14
      - wcwidth==0.2.14
prefix: /scr/benpry/conda/envs/rd-culture
