n_betas: 30
n_generations: 20
n_observations: 1
max_val: 21
dimension: 3
true_probs: [0.9, 0.07, 0.03]
max_beta: 10
save_file_name: dirichlet_categorical_farthertrueprobs
source_distribution: uniform
distortion_metric: jeff_divergence
